[pytest]
addopts = --ds=config.settings.test --strict-markers --tb=short -vv
python_files = tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
